grafana_logs_dir: "/var/log/grafana"
grafana_data_dir: "/var/lib/grafana"

grafana_address: "0.0.0.0"
grafana_port: 3000

grafana_admin_password: "P@ssw0rd"

grafana_datasources: 
  - name: "Prometheus"
    type: "prometheus"
    access: "proxy"
    url: "http://localhost:9090"
    isDefault: true

grafana_dashboards: 
  - dashboard_id: '3662'
    revision_id: '2'
    datasource: 'Prometheus'
  - dashboard_id: '1860'
    revision_id: '27'
    datasource: 'Prometheus'
  - dashboard_id: '9578'
    revision_id: '4'
    datasource: 'Prometheus'
  - dashboard_id: '9628'
    revision_id: '7'
    datasource: 'Prometheus'
  - dashboard_id: '4271' #docker
    revision_id: '4'
    datasource: 'Prometheus'
  - dashboard_id: '7362' #mysql Overview
    revision_id: '5'
    datasource: 'Prometheus'
  - dashboard_id: '2428' #nginx haproxy
    revision_id: '7'
    datasource: 'Prometheus'
  - dashboard_id: '15211' #mysql
    revision_id: '1'
    datasource: 'Prometheus'
grafana_dashboards_dir: "dashboards"

grafana_provisioning_synced: false