---
- name: Create the prometheus group
  group:
    name: "{{ prometheus_group }}"
    state: present
    system: true

- name: Create User prometheus
  user:
    name: "{{ prometheus_user }}"
    create_home: no
    shell: /bin/false

- name: Create directories for prometheus
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_user }}"
  loop:
    - '/tmp/prometheus'
    - '{{ prometheus_config_dir }}'
    - '/var/lib/prometheus'

- name: Download And Unzipped Prometheus
  unarchive:
    src: https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz
    dest: /tmp/prometheus
    creates: /tmp/prometheus/prometheus-{{ prometheus_version }}.linux-amd64
    remote_src: yes

- name: Copy Bin Files From Unzipped to Prometheus
  copy:
    src: /tmp/prometheus/prometheus-{{ prometheus_version }}.linux-amd64/{{ item }}
    dest: /usr/local/bin/
    remote_src: yes
    mode: preserve
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_user }}"
  loop: [ 'prometheus', 'promtool' ]

- name: Copy Conf Files From Unzipped to Prometheus
  copy:
    src: /tmp/prometheus/prometheus-{{ prometheus_version }}.linux-amd64/{{ item }}
    dest: {{ prometheus_config_path }}/
    remote_src: yes
    mode: preserve
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_user }}"
  loop: [ 'console_libraries', 'consoles']

- name: Create File for Prometheus Systemd
  template:
    src=templates/prometheus.service.j2
    dest=/etc/systemd/system/prometheus.service
  notify:
    - restart prometheus

- name: copy config
  template:
    src=templates/prometheus.yml.j2
    dest={{ prometheus_config_dir }}/prometheus.yml
  notify:
    - restart prometheus

- name: copy alert
  template:
    src=templates/rules.yml.j2
    dest={{ prometheus_config_dir }}/rules.yml
  notify:
    - restart prometheus

- name: Systemctl Prometheus Start
  systemd:
    name: prometheus
    state: started
    enabled: yes

- import_tasks: alertmanager.yml